### PR TITLE
Cms/v2.2.0

### PR DESCRIPTION
**Pull request by pmillet**
PR as explained in
https://github.com/cms-externals/sherpa/pull/2

### CODE REVIEW

**Comment by pmillet** [comment]
@degano could you accept this too?

**Comment by degano** [comment]
@pmillet I'll be testing this now.

**Comment by degano** [comment]
+1
Tested here: https://github.com/cms-sw/cmsdist/pull/1959

**Comment by smuzaffar** [comment]
@pmillet , is now sherpa not support -j option? I see we get this error 
```
Unrecognized option '-j1'.

Usage:

  Sherpa [options] [=] [:=]
```
Full log file is  given below. We get this error while running cmssw workflow 534.0
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2015-11-16-2300/pyRelValMatrixLogs/run/534.0_sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+HARVESTGEN/step1_sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+HARVESTGEN.log

**Comment by pmillet** [comment]
@smuzaffar It seems that this option has been removed in Sherpa v2.2.0. We will update the interface accordingly.

**Comment by thuer** [comment]
We fixed the interface to remove this option in the call
https://github.com/cms-sw/cmssw/pull/12462

The changes to the tarball retrieving are not merged (https://github.com/cms-sw/cmssw/pull/11985 was 7_6_X). Should I cherry pick these commits on top and update the RelVal files? Otherwise we mix sherpa versions

**Pull request merged**
