### PR TITLE
Cms/v2.2.4

### PR DESCRIPTION
**Pull request by pmillet**
-new sherpa version
-needed for 2017 MC production
-this branch contains the cms-sw modifications on top of the raw tarball content

- for the update of cmsdist: it would be important that the sherpa version is updated on top of https://github.com/cms-sw/cmsdist/pull/3367 (currently only in 93X devel branch, should go to 94X and 93X)
- would you prefer if I do the combined PR to cmsdist myself, or to do it yourself?

(as discussed in https://github.com/cms-externals/sherpa/pull/10)

### CODE REVIEW

**Comment by mrodozov** [comment]
I'd prefer if you provide it, so please go ahead

**Comment by smuzaffar** [comment]
@mrodozov , please note that there is already https://github.com/cms-sw/cmsdist/pull/3392 which include sherpa changes @pmillet mentioned

**Comment by pmillet** [comment]
@smuzaffar Ah ok I missed this, thanks for mentioning it!

**Comment by pmillet** [comment]
since https://github.com/cms-sw/cmsdist/pull/3392 is merged now, could you update the version/tag/commit in 94x ?

**Comment by mrodozov** [comment]
Hi there, Shahzad already did it and the tests are ongoing here https://github.com/cms-sw/cmsdist/pull/3405. When the tests are passed we would change the version also for 93

**Comment by pmillet** [comment]
perfect

**Pull request merged**
